CREATE TABLE PRODUCT (
	ID INT NOT NULL AUTO_INCREMENT,
	TYPE VARCHAR(1000) NOT NULL, 
	IMG VARCHAR(1000) NOT NULL, 
	DESCRIPTION VARCHAR(1000) NOT NULL, 
	RATING INT NOT NULL, 
	PRICE DECIMAL(9, 2) NOT NULL, 
	OLD_PRICE DECIMAL(9, 2), 
	NEW BOOLEAN, 
	OUT_OF_STOCK BOOLEAN, 
	SALE BOOLEAN,
	PRIMARY KEY ( ID )
);